framework:
    messenger:
        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            high_priority:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%&queue_name=high'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 4
                    multiplier: 2
            normal_priority:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%&queue_name=normal'
                retry_strategy:
                    max_retries: 2
                    multiplier: 3
            failed: 'doctrine://default?queue_name=failed'
            sync: 'sync://'

        failure_transport: failed

        default_bus: messenger.bus.default

        buses:
            messenger.bus.default:
                middleware:
                    - App\Middleware\PriorityRoutingMiddleware
                    - App\Middleware\LoggingMiddleware

            command.bus:
                default_middleware: false
                middleware:
                    - 'add_bus_name_stamp_middleware'
                    - App\Middleware\PriorityRoutingMiddleware
                    - App\Middleware\LoggingMiddleware
                    - 'validation'
                    - 'handle_message'
                    - 'doctrine_transaction'

            query.bus:
                default_middleware: false
                middleware:
                    - App\Middleware\LoggingMiddleware
                    - 'handle_message'

        routing:
            Symfony\Component\Mailer\Messenger\SendEmailMessage: normal_priority
            Symfony\Component\Notifier\Message\ChatMessage: normal_priority
            Symfony\Component\Notifier\Message\SmsMessage: normal_priority
            App\Message\MatchVolunteerMessage: normal_priority

            # Route your messages to the transports
            # 'App\Message\YourMessage': async
